### ISSUE TITLE
M_PI issue - core_scanner.c

### ISSUE THREAD

**Issue by TheGreatFox** [SINGROUP/PyVAFM#1]
When attempting to compile, it appears an old fix was removed and the M_PI issue returned. 

core_scanner.c: In function ‘DoSinScan’:
core_scanner.c:397:58: error: ‘M_PI’ undeclared (first use in this function)
     GlobalBuffers[c->outputs[2]] = c->params[9] +  cos(2*M_PI*c->iparams[1]*dt*c->params[10])*c->params[11];
                                                          ^
core_scanner.c:397:58: note: each undeclared identifier is reported only once for each function it appears in
make: *** [scanner] Error 1

**Comment by DrSpacemanMD** [comment]
Hey!

So for some reason I found that some c compilers don't have the M_PI variable. Anyway I have fixed it and updated the git hub. So please re-download and try again then let me know if you have any issues thanks.

John

**Comment by TheGreatFox** [comment]
Thanks for the correction. Issue resolved.

**Comment by DrSpacemanMD** [comment]
awesome thanks for the heads up.

John


On 21 Dec 2016, at 14:36, TheGreatFox <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the correction. Issue resolved.
